build-job:
  stage: build
  image: python:3.12-alpine
  variables:
    SECURE_FILES_DOWNLOAD_PATH: rm_analyzer/
  script: 
    - pip install -r requirements.txt
    - pip install pyinstaller
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - pyinstaller cli.py --name rma --add-data rm_analyzer/credentials.json:rm_analyzer --onefile
  artifacts:
    paths:
      - dist/